---
system_asn: 4200000204
system_loopback_ipv4: 10.1.2.4/32
system_loopback_ipv6: 2001:db8::4/128
frr_system_uplinks:
  - eth1
  - eth2
nm_connection_uplinks:
  - "Wired connection 1"
  - "Wired connection 2"
